export interface TablePage {
    decoder: string;
    evidenceState: "pending" | "ported" | "reconciled";
    name: string;
    sourceLedger: boolean;
    type: "bss" | "dbss" | "loc";
}

export const tablePages = [
    {
        decoder: "acceptquest.bss.ts",
        evidenceState: "ported",
        name: "acceptquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "alchemystatdata.bss.ts",
        evidenceState: "ported",
        name: "alchemystatdata.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "allquestlist.bss.ts",
        evidenceState: "ported",
        name: "allquestlist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "barter_npclist.ts",
        evidenceState: "pending",
        name: "barter_npclist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "base_dialog.dbss.ts",
        evidenceState: "ported",
        name: "base_dialog.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "base_dialogoffset.dbss.ts",
        evidenceState: "ported",
        name: "base_dialogoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "branchquest.bss.ts",
        evidenceState: "pending",
        name: "branchquest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "characteraudioradius.dbss.ts",
        evidenceState: "pending",
        name: "characteraudioradius.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "characteraudioradiusoffset.dbss.ts",
        evidenceState: "pending",
        name: "characteraudioradiusoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "characterfunction.ts",
        evidenceState: "ported",
        name: "characterfunction.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterfunctionoffset.dbss.ts",
        evidenceState: "ported",
        name: "characterfunctionoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterobject.dbss.ts",
        evidenceState: "reconciled",
        name: "characterobject.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterobjectoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterobjectoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "charactersimply.bss.ts",
        evidenceState: "reconciled",
        name: "charactersimply.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "characterspawntype.dbss.ts",
        evidenceState: "reconciled",
        name: "characterspawntype.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterspawntypeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterspawntypeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterstaticoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterstaticoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "completequest.bss.ts",
        evidenceState: "ported",
        name: "completequest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "contentsgroupoptionstaticstatusmanager.bss.ts",
        evidenceState: "reconciled",
        name: "contentsgroupoptionstaticstatusmanager.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "cookingstatdata.bss.ts",
        evidenceState: "reconciled",
        name: "cookingstatdata.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "cutscenecharacterdata.bss.ts",
        evidenceState: "reconciled",
        name: "cutscenecharacterdata.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "detail_dialog.dbss.ts",
        evidenceState: "reconciled",
        name: "detail_dialog.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "detail_dialogoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "detail_dialogoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "dialogtext.dbss.ts",
        evidenceState: "reconciled",
        name: "dialogtext.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "dialogtextoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "dialogtextoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "displayexchangeitemnpc.dbss.ts",
        evidenceState: "reconciled",
        name: "displayexchangeitemnpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "displayexchangeitemnpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "displayexchangeitemnpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "doguildquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "doguildquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "employeecharactership.dbss.ts",
        evidenceState: "reconciled",
        name: "employeecharactership.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "employeecharactershipoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "employeecharactershipoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "enchantstaticstatus.dbss.ts",
        evidenceState: "reconciled",
        name: "enchantstaticstatus.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "enchantstaticstatusoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "enchantstaticstatusoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "extractitem.dbss.ts",
        evidenceState: "reconciled",
        name: "extractitem.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "extractitemoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "extractitemoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "feverquestdatatable.bss.ts",
        evidenceState: "reconciled",
        name: "feverquestdatatable.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "growthpassquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "growthpassquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "guildhousecraftskill.dbss.ts",
        evidenceState: "reconciled",
        name: "guildhousecraftskill.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildhousecraftskilloffset.dbss.ts",
        evidenceState: "reconciled",
        name: "guildhousecraftskilloffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildhousecraftskillreverselinklist.bss.ts",
        evidenceState: "reconciled",
        name: "guildhousecraftskillreverselinklist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "guildhousecraftstorage.dbss.ts",
        evidenceState: "reconciled",
        name: "guildhousecraftstorage.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildhousecraftstorageoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "guildhousecraftstorageoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildmanufacture.dbss.ts",
        evidenceState: "reconciled",
        name: "guildmanufacture.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildmanufactureoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "guildmanufactureoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildquest.dbss.ts",
        evidenceState: "reconciled",
        name: "guildquest.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "guildquestoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "guildquestoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "houseinfoneeditem.dbss.ts",
        evidenceState: "reconciled",
        name: "houseinfoneeditem.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "houseinfoneeditemoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "houseinfoneeditemoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "houseinforeceipe.dbss.ts",
        evidenceState: "reconciled",
        name: "houseinforeceipe.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "houseinforeceipeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "houseinforeceipeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemenchant.dbss.ts",
        evidenceState: "reconciled",
        name: "itemenchant.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemenchantoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemenchantoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemequipgroup.bss.ts",
        evidenceState: "reconciled",
        name: "itemequipgroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangebynpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangebynpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangebynpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangebynpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangesource.bss.ts",
        evidenceState: "reconciled",
        name: "itemexchangesource.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangetoclass.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclass.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangetoclassmapkey.bss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclassmapkey.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangetoclassoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclassoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovement.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovement.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementdefaultdisplaylist.bss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementdefaultdisplaylist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemimprovementoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementsource.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementsource.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementsourceoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementsourceoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemlinkprice.bss.ts",
        evidenceState: "reconciled",
        name: "itemlinkprice.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmaingroup.bss.ts",
        evidenceState: "reconciled",
        name: "itemmaingroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmarketcategory.bss.ts",
        evidenceState: "reconciled",
        name: "itemmarketcategory.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmaxlevel.dbss.ts",
        evidenceState: "reconciled",
        name: "itemmaxlevel.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemmaxleveloffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemmaxleveloffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemsubgroup.dbss.ts",
        evidenceState: "reconciled",
        name: "itemsubgroup.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemsubgroupoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemsubgroupoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtrade.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtrade.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradeetc.bss.ts",
        evidenceState: "reconciled",
        name: "itemtradeetc.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemtradegroupfromnpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegroupfromnpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegroupfromnpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegroupfromnpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegrouptonpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegrouptonpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegrouptonpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegrouptonpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "journalquest.dbss.ts",
        evidenceState: "pending",
        name: "journalquest.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "journalquestoffset.dbss.ts",
        evidenceState: "pending",
        name: "journalquestoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "knowledgelearning.dbss.ts",
        evidenceState: "reconciled",
        name: "knowledgelearning.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "knowledgelearningcharacterkey.bss.ts",
        evidenceState: "reconciled",
        name: "knowledgelearningcharacterkey.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "knowledgelearningoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "knowledgelearningoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "languagedata.loc.ts",
        evidenceState: "reconciled",
        name: "languagedata.loc",
        sourceLedger: true,
        type: "loc",
    },
    {
        decoder: "mainquest.bss.ts",
        evidenceState: "ported",
        name: "mainquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "manufacture.bss.ts",
        evidenceState: "reconciled",
        name: "manufacture.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "manufacturecondition.dbss.ts",
        evidenceState: "reconciled",
        name: "manufacturecondition.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "manufactureconditionoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "manufactureconditionoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "manufactureitemnaminginfo.bss.ts",
        evidenceState: "reconciled",
        name: "manufactureitemnaminginfo.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "manufacturingstat.bss.ts",
        evidenceState: "reconciled",
        name: "manufacturingstat.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "marketsearchlist.bss.ts",
        evidenceState: "reconciled",
        name: "marketsearchlist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "mentalcard.dbss.ts",
        evidenceState: "reconciled",
        name: "mentalcard.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "mentalcardoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "mentalcardoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "mentaltheme.dbss.ts",
        evidenceState: "reconciled",
        name: "mentaltheme.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "mentalthemeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "mentalthemeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "multiplequest.bss.ts",
        evidenceState: "pending",
        name: "multiplequest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "newquest.bss.ts",
        evidenceState: "ported",
        name: "newquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "normalgroupquest.bss.ts",
        evidenceState: "pending",
        name: "normalgroupquest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "npcgift.dbss.ts",
        evidenceState: "pending",
        name: "npcgift.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftdata.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftdata.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftdataoffset.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftdataoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftetc.bss.ts",
        evidenceState: "pending",
        name: "npcgiftetc.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "npcgiftoffset.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcpersonality.dbss.ts",
        evidenceState: "ported",
        name: "npcpersonality.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "npcpersonalityoffset.dbss.ts",
        evidenceState: "ported",
        name: "npcpersonalityoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "npcsimply.bss.ts",
        evidenceState: "ported",
        name: "npcsimply.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "olviaacademycurriculumquestlist.bss.ts",
        evidenceState: "pending",
        name: "olviaacademycurriculumquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "olviaacademypassquestlist.bss.ts",
        evidenceState: "pending",
        name: "olviaacademypassquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "olviaacademyrewardquestlistt.bss.ts",
        evidenceState: "pending",
        name: "olviaacademyrewardquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "quest.dbss.ts",
        evidenceState: "ported",
        name: "quest.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "questgroup.dbss.ts",
        evidenceState: "pending",
        name: "questgroup.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "questjournalvideoinfo.bss.ts",
        evidenceState: "pending",
        name: "questjournalvideoinfo.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "questprogressgroup.bss.ts",
        evidenceState: "pending",
        name: "questprogressgroup.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "questrandomgroup.bss.ts",
        evidenceState: "ported",
        name: "questrandomgroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "recommendationquest.bss.ts",
        evidenceState: "reconciled",
        name: "recommendationquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "regionmonsterkillquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "regionmonsterkillquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "repairmaxendurance.dbss.ts",
        evidenceState: "reconciled",
        name: "repairmaxendurance.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "repairmaxenduranceoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "repairmaxenduranceoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "repetitionquest.bss.ts",
        evidenceState: "reconciled",
        name: "repetitionquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "seasonpassquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "seasonpassquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "seasonpassquestlistforcash.bss.ts",
        evidenceState: "reconciled",
        name: "seasonpassquestlistforcash.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "seasonpassquestlistfornormal.bss.ts",
        evidenceState: "reconciled",
        name: "seasonpassquestlistfornormal.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "specialquestinfo.bss.ts",
        evidenceState: "reconciled",
        name: "specialquestinfo.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "specialquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "specialquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "supplyservantquestlist.bss.ts",
        evidenceState: "reconciled",
        name: "supplyservantquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "totalquestcountregion.bss.ts",
        evidenceState: "reconciled",
        name: "totalquestcountregion.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "totalquestcounttype.bss.ts",
        evidenceState: "reconciled",
        name: "totalquestcounttype.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "usernpc.bss.ts",
        evidenceState: "reconciled",
        name: "usernpc.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "worldquest.dbss.ts",
        evidenceState: "pending",
        name: "worldquest.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "yachtnpcdiceinfo.bss.ts",
        evidenceState: "reconciled",
        name: "yachtnpcdiceinfo.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "zodiacsignorder.dbss.ts",
        evidenceState: "reconciled",
        name: "zodiacsignorder.dbss",
        sourceLedger: true,
        type: "dbss",
    },
] as const satisfies readonly TablePage[];
