export interface TablePage {
    decoder: string;
    evidenceState: "pending" | "ported" | "reconciled";
    name: string;
    sourceLedger: boolean;
    type: "bss" | "dbss";
}

export const tablePages = [
    {
        decoder: "acceptquest.bss.ts",
        evidenceState: "ported",
        name: "acceptquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "alchemystatdata.bss.ts",
        evidenceState: "ported",
        name: "alchemystatdata.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "allquestlist.bss.ts",
        evidenceState: "ported",
        name: "allquestlist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "barter_npclist.ts",
        evidenceState: "pending",
        name: "barter_npclist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "base_dialog.dbss.ts",
        evidenceState: "ported",
        name: "base_dialog.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "base_dialogoffset.dbss.ts",
        evidenceState: "ported",
        name: "base_dialogoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "branchquest.bss.ts",
        evidenceState: "pending",
        name: "branchquest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "characteraudioradius.dbss.ts",
        evidenceState: "pending",
        name: "characteraudioradius.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "characteraudioradiusoffset.dbss.ts",
        evidenceState: "pending",
        name: "characteraudioradiusoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "characterfunction.ts",
        evidenceState: "ported",
        name: "characterfunction.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterfunctionoffset.dbss.ts",
        evidenceState: "ported",
        name: "characterfunctionoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterobject.dbss.ts",
        evidenceState: "reconciled",
        name: "characterobject.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterobjectoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterobjectoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "charactersimply.bss.ts",
        evidenceState: "reconciled",
        name: "charactersimply.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "characterspawntype.dbss.ts",
        evidenceState: "reconciled",
        name: "characterspawntype.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterspawntypeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterspawntypeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "characterstaticoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "characterstaticoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "completequest.bss.ts",
        evidenceState: "ported",
        name: "completequest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemenchant.dbss.ts",
        evidenceState: "reconciled",
        name: "itemenchant.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemenchantoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemenchantoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemequipgroup.bss.ts",
        evidenceState: "reconciled",
        name: "itemequipgroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangebynpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangebynpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangebynpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangebynpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangesource.bss.ts",
        evidenceState: "reconciled",
        name: "itemexchangesource.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangetoclass.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclass.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemexchangetoclassmapkey.bss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclassmapkey.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemexchangetoclassoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemexchangetoclassoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovement.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovement.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementdefaultdisplaylist.bss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementdefaultdisplaylist.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemimprovementoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementsource.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementsource.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemimprovementsourceoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemimprovementsourceoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemlinkprice.bss.ts",
        evidenceState: "reconciled",
        name: "itemlinkprice.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmaingroup.bss.ts",
        evidenceState: "reconciled",
        name: "itemmaingroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmarketcategory.bss.ts",
        evidenceState: "reconciled",
        name: "itemmarketcategory.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemmaxlevel.dbss.ts",
        evidenceState: "reconciled",
        name: "itemmaxlevel.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemmaxleveloffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemmaxleveloffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemsubgroup.dbss.ts",
        evidenceState: "reconciled",
        name: "itemsubgroup.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemsubgroupoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemsubgroupoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtrade.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtrade.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradeetc.bss.ts",
        evidenceState: "reconciled",
        name: "itemtradeetc.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "itemtradegroupfromnpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegroupfromnpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegroupfromnpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegroupfromnpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegrouptonpc.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegrouptonpc.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradegrouptonpcoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradegrouptonpcoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "itemtradeoffset.dbss.ts",
        evidenceState: "reconciled",
        name: "itemtradeoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "journalquest.dbss.ts",
        evidenceState: "pending",
        name: "journalquest.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "journalquestoffset.dbss.ts",
        evidenceState: "pending",
        name: "journalquestoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "mainquest.bss.ts",
        evidenceState: "ported",
        name: "mainquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "multiplequest.bss.ts",
        evidenceState: "pending",
        name: "multiplequest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "newquest.bss.ts",
        evidenceState: "ported",
        name: "newquest.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "normalgroupquest.bss.ts",
        evidenceState: "pending",
        name: "normalgroupquest.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "npcgift.dbss.ts",
        evidenceState: "pending",
        name: "npcgift.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftdata.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftdata.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftdataoffset.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftdataoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcgiftetc.bss.ts",
        evidenceState: "pending",
        name: "npcgiftetc.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "npcgiftoffset.dbss.ts",
        evidenceState: "pending",
        name: "npcgiftoffset.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "npcpersonality.dbss.ts",
        evidenceState: "ported",
        name: "npcpersonality.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "npcpersonalityoffset.dbss.ts",
        evidenceState: "ported",
        name: "npcpersonalityoffset.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "npcsimply.bss.ts",
        evidenceState: "ported",
        name: "npcsimply.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "olviaacademycurriculumquestlist.bss.ts",
        evidenceState: "pending",
        name: "olviaacademycurriculumquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "olviaacademypassquestlist.bss.ts",
        evidenceState: "pending",
        name: "olviaacademypassquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "olviaacademyrewardquestlistt.bss.ts",
        evidenceState: "pending",
        name: "olviaacademyrewardquestlist.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "quest.dbss.ts",
        evidenceState: "ported",
        name: "quest.dbss",
        sourceLedger: true,
        type: "dbss",
    },
    {
        decoder: "questgroup.dbss.ts",
        evidenceState: "pending",
        name: "questgroup.dbss",
        sourceLedger: false,
        type: "dbss",
    },
    {
        decoder: "questjournalvideoinfo.bss.ts",
        evidenceState: "pending",
        name: "questjournalvideoinfo.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "questprogressgroup.bss.ts",
        evidenceState: "pending",
        name: "questprogressgroup.bss",
        sourceLedger: false,
        type: "bss",
    },
    {
        decoder: "questrandomgroup.bss.ts",
        evidenceState: "ported",
        name: "questrandomgroup.bss",
        sourceLedger: true,
        type: "bss",
    },
    {
        decoder: "worldquest.dbss.ts",
        evidenceState: "pending",
        name: "worldquest.dbss",
        sourceLedger: false,
        type: "dbss",
    },
] as const satisfies readonly TablePage[];
